---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      provider: fabric8
      app: vertx-default-sample
      version: "@ignore@"
      group: io.fabric8
    name: vertx-default-sample
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: vertx-default-sample
      provider: fabric8
      group: io.fabric8
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      provider: fabric8
      app: vertx-default-sample
      version: "@ignore@"
      group: io.fabric8
    name: vertx-default-sample
  spec:
    replicas: 1
    selector:
      app: vertx-default-sample
      provider: fabric8
      group: io.fabric8
    template:
      metadata:
        labels:
          provider: fabric8
          app: vertx-default-sample
          version: "@ignore@"
          group: io.fabric8
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: "@matches('fabric8/vertx-default-sample:.*$')@"
          imagePullPolicy: IfNotPresent
          name: vertx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
