
[[fabric8:watch-spring-boot]]
== *fabric8:watch-spring-boot*

This goal tails the log of the latest running pod for your application and watches the local development build of your Spring Boot based application and then triggers a reload of the application when there are changes.

Before using this goal you need to add the `spring.devtools.remote.secret` property into your `application.properties` file like the following example. You can use any value you like.

[source, sh]
----
spring.devtools.remote.secret=mysecrettoken
----

then deploy your app:

[source, sh]
----
mvn fabric8:deploy
----

Now you can watch the container and restart it on local code changes via:

[source, sh]
----
mvn fabric8:watch-spring-boot
----

Once the goal starts up the spring boot RemoteSpringApplication it will watch for local development changes.

e.g. if you edit the java code of your app and then build it via something like this:

[source, sh]
----
mvn package
----

You should see your app reload on the fly in the shell running the <<fabric8:watch-spring-boot>> goal

