---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: sample-svc
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: project
      provider: provider
      group: group
    type: NodePort
  # strict checking: no other attributes will be added
