---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: "@ignore@"
      prometheus.io/scrape: "true"
      fabric8.io/git-branch: "@ignore@"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      provider: fabric8
      app: fabric8-maven-sample-env-metadata
      version: "@ignore@"
      group: io.fabric8
    name: fabric8-maven-sample-env-metadata
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: fabric8-maven-sample-env-metadata
      provider: fabric8
      group: io.fabric8
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: "@ignore@"
      fabric8.io/metrics-path: "@matches('.*dashboard.*fabric8-maven-sample-env-metadata.*var-version.*')@"
      fabric8.io/git-branch: "@ignore@"
    labels:
      provider: fabric8
      app: fabric8-maven-sample-env-metadata
      version: "@ignore@"
      group: io.fabric8
    name: fabric8-maven-sample-env-metadata
  spec:
    replicas: 1
    selector:
      app: fabric8-maven-sample-env-metadata
      provider: fabric8
      group: io.fabric8
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "@ignore@"
          fabric8.io/metrics-path: "@matches('.*dashboard.*fabric8-maven-sample-env-metadata.*var-version.*')@"
          fabric8.io/git-branch: "@ignore@"
        labels:
          provider: fabric8
          app: fabric8-maven-sample-env-metadata
          version: "@ignore@"
          group: io.fabric8
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_ENV_key
            value: MY_ENV_value
          image: "@matches('fabric8/fabric8-maven-sample-env-metadata:.*$')@"
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
