
[[enrichers]]
= Enrichers

Enriching is the complementary concept to <<generators, Generators>>. Whereas Generators are used to create and customize Docker images, Enrichers are use to create and customize Kubernetes and OpenShift resource objects.

There are a lot of similarities to Generators:

* Each Enricher has a unique name.
* Enrichers are looked up automatically from the plugin dependencies and there is a set of default enrichers delivered with this plugin.
* Enrichers are configured the same ways as generators

The <<generator-example,Generator example>> is a good bluebprint, simply replace `<generator>` with `<enricher>`. The configuration is structural identical:

.Enricher configuration
[cols="2,6"]
|===
| Element | Description

| `<includes>`
| Contains one ore more `<include>` elements with enricher names which should be included. If given, only this list of enrichers are included in this order. The enrichers from every active profile are included, too. However the enrichers listed here are moved to the front of the list, so that they are called first. Use the profile `raw` if you want to explicitly set the complete list of enrichers.

| `<excludes>`
| Holds one or more `<exclude>` elements with enricher names to exclude. This means all the detected enrichers are used except the ones mentioned in this section.

| `<config>`
| Configuration for all enrichers. Each enricher supports a specific set of configuration values as described in its documentation. The subelements of this section are enricher names. E.g. for enricher `f8-service`, the sub-element is called `<f8-service>`. This element then holds the specific enricher configuration like `<name>` for the service name. Configuration coming from profiles are merged into this config, but not overriding the configuration specified here.
|===

This plugin comes with a set of default enrichers. In addition custom enrichers can be easily added by providing implementation of the <<enricher-api, Enricher API>> and adding these as a dependency to the build.

[[enrichers-default]]
== Default Enrichers

fabric8-maven-plugin comes with a set of enrichers which are enabled by default. There are two categories of default enrichers:

* *Standard Enrichers* are used to add default resource object when they are missing or add common metadata extracted from the given build information
* *Fabric8 Enrichers* are specific to the https://fabric8.io[fabric8 Microservice's platform]. It adds icon annotations which are visible in the fabric8 console or connections to the Continous Deliverys systems like Jenkins or Gogs.

. Default Enrichers Overview
[cols="2,7"]
|===
| Enricher | Description

| <<f8-cd>>
| Add CD metadata as annotations.

| <<f8-doc-link>>
| Add URL to documentation configured in the POM as annotation.

| <<f8-grafana-link>>
| Add a Grafana Dashboard URL as annotation.

| <<f8-icon>>
| Add an URL to icons for well known application types.

| <<f8-prometheus>>
| Add Prometheus annotations.

| <<f8-maven-scm-enricher>>
| Add Maven SCM information as annotations to the kubernetes/openshift resources

| <<fmp-controller>>
| Create default controller (replication controller, replica set or deployment) if missing.

| <<fmp-dependency>>
| Examine build dependencies for `kubernetes.yml` and add the objects found therein.

| <<fmp-git>>
| Check local `.git` directory and add build information as annotations.

| <<fmp-ianaservice>>
| Add a default portname looking up IANA services

| <<fmp-image>>
| Add the image name into a `PodSpec` of replication controller, replication sets and deployments, if missing.

| <<fmp-name>>
| Add a default name to every object which misses a name.

| <<fmp-pod-annotation>>
| Copy over annotations from a `Deployment` to a `Pod`

| <<fmp-portname>>
| Add a default portname for commonly known service.

| <<fmp-project>>
| Add Maven coordinates as labels to all objects.

| <<fmp-service>>
| Create a default service if missing and extrac ports from the Docker image configuration.

| <<fmp-maven-issue-mgmt-enricher>>
| Add Maven Issue Management information as annotations to the kubernetes/openshift resources

| <<fmp-revision-history-enricher>>
| Add revision history limit (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit[Kubernetes doc]) as a deployment spec property to the Kubernetes/OpenShift resources.
|===

[[enrichers-standard]]
=== Standard Enrichers

Default enrichers are used for adding missing resources or adding metadata to given resource objects. The following default enhancers are available out of the box

[[fmp-controller]]
==== fmp-controller

include::enricher/_fmp_service.adoc[]

[[fmp-image]]
==== fmp-image

[[fmp-name]]
==== fmp-name

[[fmp-portname]]
==== fmp-portname

[[fmp-pod-annotation]]
==== fmp-pod-annotation

[[fmp-ianaservice]]
==== fmp-ianaservice

[[fmp-project]]
==== fmp-project

Enricher that adds standard labels and selectors to generated resources (e.g. `app`, `group`, `provider`, `version`).

The `fmp-project` enricher supports the following configuration options:

[cols="2,6,3"]
|===
| Option | Description | Default

| `useProjectLabel`
| Enable this flag to turn on the generation of the old `project` label in Kubernetes resources. The `project` label has been replaced by the `app` label in newer versions of the plugin.
| `false`
|===

[[fmp-git]]
==== fmp-git

[[fmp-dependency]]
==== fmp-dependency

[[fmp-volume-permission]]
==== fmp-volume-permission

Enricher which fixes the permission of persistent volume mount with the help of an init container.

[[fmp-autotls]]
==== fmp-autotls

Enricher which adds appropriate annotations and volumes to enable OpenShift's automatic https://docs.openshift.org/latest/dev_guide/secrets.html#service-serving-certificate-secrets[Service Serving Certificate Secrets].
This enricher adds an init container to convert the service serving certificates from PEM (the format that OpenShift generates them in) to
a JKS-format Java keystore ready for consumption in Java services.

This enricher is disabled by default. In order to use it, you must configure the Fabric8 Maven plugin to use this enricher:

[source,xml]
----
<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-maven-plugin</artifactId>
  <version>3.3.0</version>
  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <enricher>
      <includes>
        <include>fmp-autotls</include>
      </includes>
      <config>
        <fmp-autotls>
          ...
        </fmp-autotls>
      </config>
    </enricher>
  </configuration>
</plugin>
----

The auto-TLS enricher supports the following configuration options:

[cols="2,6,3"]
|===
| Option | Description | Default

| `tlsSecretName`
| The name of the secret to be used to store the generated service serving certs.
| `<project.artifactId>-tls`

| `tlsSecretVolumeMountPoint`
| Where the service serving secret should be mounted to in the pod.
| `/var/run/secrets/fabric8.io/tls-pem`

| `tlsSecretVolumeName`
| The name of the secret volume.
| `tls-pem`

| `jksVolumeMountPoint`
| Where the generated keystore volume should be mounted to in the pod.
| `/var/run/secrets/fabric8.io/tls-jks`

| `jksVolumeName`
| The name of the keystore volume.
| `tls-jks`

| `pemToJKSInitContainerImage`
| The name of the image used as an init container to convert PEM certificate/key to Java keystore.
| `jimmidyson/pemtokeystore:v0.1.0`

| `pemToJKSInitContainerName`
| the name of the init container to convert PEM certificate/key to Java keystore.
| `tls-jks-converter`

| `keystoreFileName`
| The name of the generated keystore file.
| `keystore.jks`

| `keystorePassword`
| The password to use for the generated keystore.
| `changeit`

| `keystoreCertAlias`
| The alias in the keystore used for the imported service serving certificate.
| `server`
|===

[[enrichers-fabric8]]
=== Fabric8 Enrichers

Fabric8 enrichers are used for providing the connection to other components of the fabric8 Microservices platform. They are useful to add icons to to application or links to documentation sites.

[[f8-cd]]
==== f8-cd

[[f8-doc-link]]
==== f8-doc-link

[[f8-grafana-link]]
==== f8-grafana-link

[[f8-icon]]
==== f8-icon

[[f8-karaf-health-check]]
==== f8-karaf-health-check

This enricher adds kubernetes readiness and liveness probes with Apache Karaf. This requires that
 `fabric8-karaf-checks` has been enabled in the Karaf startup features.

The enricher will use the following settings by default:

- port = `8181`
- scheme = `HTTP`

and use paths `/readiness-check` for readiness check and `/health-check` for liveness check.

These options cannot be configured.

[[f8-prometheus]]
==== f8-prometheus

This enricher adds Prometheus annotation like:

[source,yaml]
----
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: 9779
----

By default the enricher inspects the images' BuildConfiguration and add the annotations if the port 9779 is listed.
You can force the plugin to add annotations by setting enricher's config ```prometheusPort```

[[f8-spring-boot-health-check]]
==== f8-spring-boot-health-check

This enricher adds kubernetes readiness and liveness probes with Spring Boot. This requires the following dependency
 has been enabled in Spring Boot

[source,xml]
   <dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-actuator</artifactId>
   </dependency>

The enricher will try to discover the settings from the `application.properties` / `application.yaml` Spring Boot
 configuration file.

The port number is read from the `management.port` option, and will use the default value of `8080`
The scheme will use HTTPS if `server.ssl.key-store` option is in use, and fallback to use `HTTP` otherwise.

These values can be configured by the enricher in the `fabric8-maven-plugin` configuration as shown below:
[source,xml]
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>3.3.0</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <spring-boot-health-check>
                <port>4444</port>
              </spring-boot-health-check>
            </config>
          </enricher>
        </configuration>
      </plugin>



[[f8-wildfly-swarm-health-check]]
==== f8-wildfly-swarm-health-check

This enricher adds kubernetes readiness and liveness probes with WildFly Swarm. This requires the following fraction
 has been enabled in WildFly Swarm

[source,xml]
   <dependency>
     <groupId>org.wildfly.swarm</groupId>
     <artifactId>monitor</artifactId>
   </dependency>

The enricher will use the following settings by default:

- port = `8080`
- scheme = `HTTP`
- path = `/health`

These values can be configured by the enricher in the `fabric8-maven-plugin` configuration as shown below:
[source,xml]
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>3.3.0</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <enricher>
            <config>
              <wildfly-swarm-health-check>
                <port>4444</port>
                <scheme>HTTPS</scheme>
                <path>health/myapp</path>
              </wildfly-swarm-health-check>
            </config>
          </enricher>
        </configuration>
      </plugin>


[[f8-vertx-health-check]]
==== f8-vertx-health-check

This enricher adds kubernetes readiness and liveness probes with Eclipse Vert.x. The readiness probe lets Kubernetes
detects when the application is ready, while the liveness probe allows Kubernetes to verify that the application is
still alive.

By default, this enricher use the same URL for liveness and readiness probes. But the readiness path can be explicitly
configured to use different paths.

The probes are added if the projects uses the Vert.x Maven Plugin or depends on the `io.vertx:vertx-core` artifact
**and** the path is explicitly configured.

The enricher will use the following settings by default:

- port = `8080`
- scheme = `HTTP`
- path = _none_ (disabled)
- readiness path = same as the path by default

To enable the health checks, configure the probed path using:

* the `vertx.health.path` project properties (`<vertx.health.path>/ping</vertx.health.path>`)
* the `path` in the `fabric8-maven-plugin` configuration:

[source, xml]
<plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>fabric8-maven-plugin</artifactId>
    <version>3.3.0</version>
    <executions>
    <execution>
    <id>fmp</id>
    <goals>
      <goal>resource</goal>
      <goal>helm</goal>
      <goal>build</goal>
    </goals>
    </execution>
    </executions>
    <configuration>
    <enricher>
    <config>
      <vertx-health-check>
        <path>/health</path>
      </vertx-health-check>
    </config>
    </enricher>
    </configuration>
</plugin>



These path, port and scheme can be configured by the enricher in the `fabric8-maven-plugin` configuration as shown below:

[source,xml]
  <plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>fabric8-maven-plugin</artifactId>
    <version>3.3.0</version>
    <executions>
      <execution>
        <id>fmp</id>
        <goals>
          <goal>resource</goal>
          <goal>helm</goal>
          <goal>build</goal>
        </goals>
      </execution>
    </executions>
    <configuration>
      <enricher>
        <config>
          <vertx-health-check>
            <port>4444</port>
            <scheme>HTTPS</scheme>
            <path>/ping</path>
            <readiness>/ping</readiness>
          </vertx-health-check>
        </config>
      </enricher>
    </configuration>
  </plugin>


Alternatively, you can use project's properties to configure the health checks:

* `vertx.health.port` - the port, 8080 by default, a negative number disables the health check
* `vertx.health.path` - the path, an empty (non null) value disables the health check.
* `vertx.health.readiness.path` - the path used for the readiness probe, an empty (non null) value disables the readiness
check. If not set it uses the regular path.
* `vertx.health.scheme` - the scheme, HTTP by default, can be set to HTTPS (adjusts the port accordingly)

By playing with the `vertx.health.path` and ``vertx.health.readiness.path` properties (and also the `<path>` and
`<readiness`> values in the configuration), you can enables or disables the check individually:

*  `vertx.health.path` not set => the health checks are disabled
*  `vertx.health.path` set to "" (empty) and `vertx.health.readiness.path` set to "/ping => the liveness check is disabled,
 the readiness check uses `GET localhost:8080/ping`
*  `vertx.health.path` set to "/ping" and `vertx.health.readiness.path` set to "" (empty) => the readiness check is
disabled, the liveness check uses `GET localhost:8080/ping`
*  `vertx.health.path` set to "/ping" and `vertx.health.readiness.path` set to "/ready"  => the readiness check uses
`GET localhost:8080/ready` , the liveness check uses the `GET localhost:8080/ping`

[[f8-maven-scm-enricher]]
==== f8-maven-scm-enricher

This enricher adds additional https://maven.apache.org/pom.html#SCM[SCM] related metadata to all objects supporting annotations.
These metadata will be added only if https://maven.apache.org/pom.html#SCM[SCM] information is present in the maven `pom.xml` of the project.

The following annotations will be added to the objects that supports annotations,

.Maven SCM Enrichers Annotation Mapping
[cols="2,2,3"]
|===
| Maven SCM Info | Annotation | Description

| scm/connection
| fabric8.io/scm-con-url
| The SCM connection that will be used to connect to the project's SCM

| scm/developerConnection
| fabric8.io/scm-devcon-url
| The SCM Developer Connection that will be used to connect to the project's developer SCM

| scm/tag
| fabric8.io/scm-tag
| The SCM tag that will be used to checkout the sources, like HEAD dev-branch etc.,

| scm/url
| fabric8.io/scm-url
| The SCM web url that can be used to browse the SCM over web browser

|===

Lets say you have a maven pom.xml with the following scm information,
[source,xml]
----
<scm>
    <connection>scm:git:git://github.com/fabric8io/fabric8-maven-plugin.git</connection>
    <developerConnection>scm:git:git://github.com/fabric8io/fabric8-maven-plugin.git</developerConnection>
    <url>git://github.com/fabric8io/fabric8-maven-plugin.git</url>
</scm>

----
This infomation will be enriched as annotations in the generated manifest like,

[source,yaml]
----
...
  kind: Service
  metadata:
    annotations
      fabric8.io/scm-con-url: "scm:git:git://github.com/fabric8io/fabric8-maven-plugin.git"
      fabric8.io/scm-devcon-url: "scm:git:git://github.com/fabric8io/fabric8-maven-plugin.git"
      fabric8.io/scm-tag: "HEAD"
      fabric8.io/scm-url: "git://github.com/fabric8io/fabric8-maven-plugin.git"
...
----

[[fmp-maven-issue-mgmt-enricher]]
==== f8-maven-issue-mgmt

This enricher adds additional https://maven.apache.org/pom.html#Issue_Management[Issue Management] related metadata to all objects supporting annotations.
These metadata will be added only if the https://maven.apache.org/pom.html#Issue_Management[Issue Management] information in available in maven `pom.xml` of the project.

The following annotations will be added to the objects that supports annotations,

.Maven Issue Tracker Enrichers Annotation Mapping
[cols="2,2,3"]
|===
| Maven Issue Tracker Info | Annotation | Description

| issueManagement/system
| fabric8.io/issue-system
| The Issue Management system like Bugzilla, JIRA, GitHub etc.,

| issueManagement/url
| fabric8.io/issue-tracker-url
| The Issue Management url e.g. GitHub Issues Url

|===

Lets say you have a maven pom.xml with the following issue management information,

[source,xml]
----
<issueManagement>
   <system>GitHub</system>
   <url>https://github.com/fabric8io/vertx-maven-plugin/issues/</url>
</issueManagement>
----

This information will be enriched as annotations in the generated manifest like,

[source,yaml]
----
...
  kind: Service
  metadata:
    annotations:
      fabric8.io/issue-system: "GitHub"
      fabric8.io/issue-tracker-url: "https://github.com/fabric8io/vertx-maven-plugin/issues/"
...
----

[[fmp-revision-history-enricher]]
==== fmp-revision-history

This enricher adds `spec.revisionHistoryLimit` property to deployment spec of Kubernetes/OpenShift resources.
A deployment’s revision history is stored in the replica sets, that specifies the number of old ReplicaSets to retain in order to allow rollback.
For more information read https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit[Kubernetes documentation].

The following configuration parameters can be used to influence the behaviour of this enricher:

.Default revision history enricher
[cols="2,2,3"]
|===
| Element | Description | Default

| limit
| Number of revision histories to retain
| 2
|===

Just as any other enricher you can specify required properties with in the enricher's configuration as below,

[source,xml]
----
...
<enricher>
    <config>
        <fmp-revision-history>
            <limit>8</limit>
        </fmp-revision-history>
    </config>
</enricher>
...
----

This information will be enriched as spec property in the generated manifest like,

[source,yaml]
----
...
kind: Deployment
spec:
  revisionHistoryLimit: 8
...
----

== Enricher API

_howto write your own enricher and install them_
