
[[enrichers]]
= Enrichers

Enriching is the complementary concept to <<generators, Generators>>. Whereas Generators are used to create and customize Docker images, Enrichers are use to create and customize Kubernetes and OpenShift resource objects.

There are a lot of similarities to Generators:

* Each Enricher has a unique name.
* Enrichers are looked up automatically from the plugin dependencies and there is a set of default enrichers delivered with this plugin.
* Enrichers are configured the same ways as generators

The <<generator-example,Generator example>> is a good bluebprint, simply replace `<generator>` with `<enricher>`. The configuration is structural identical:

.Enricher configuration
[cols="2,6"]
|===
| Element | Description

| `<includes>`
| Contains one ore more `<include>` elements with enricher names which should be included. If given, only this list of enrichers are included in this order.

| `<excludes>`
| Holds one or more `<exclude>` elements with enricher names to exclude. This means all the detected enrichers are used except the ones mentioned in this section.

| `<config>`
| Configuration for all enrichers. Each enricher supports a specific set of configuration values as described in its documentation. The subelements of this section are enricher names. E.g. for enricher `f8-service`, the sub-element is called `<f8-service>`. This element then holds the specific enricher configuration like `<name>` for the service name.
|===

This plugin comes with a set of default enrichers. In addition custom enrichers can be easily added by providing implementation of the <<enricher-api, Enricher API>> and adding these as a dependency to the build.

[[enrichers-default]]
== Default Enrichers

fabric8-maven-plugin comes with a set of enrichers which are enabled by default. There are two categories of default enrichers:

* *Standard Enrichers* are used to add default resource object when they are missing or add common metadata extracted from the given build information
* *Fabric8 Enrichers* are specific to the https://fabric8.io[fabric8 Microservice's platform]. It adds icon annotations which are visible in the fabric8 console or connections to the Continous Deliverys systems like Jenkins or Gogs.

.Default Enrichers Overview
[cols="2,7"]
|===
| Enricher | Description

| <<f8-cd>>
| Add CD metadata as annotations.

| <<f8-doc-link>>
| Add URL to documentation configured in the POM as annotation.

| <<f8-grafana-link>>
| Add a Grafana Dashboard URL as annotation.

| <<f8-icon>>
| Add an URL to icons for well known application types.

| <<fmp-controller>>
| Create default controller (replication controller, replica set or deployment) if missing.

| <<fmp-dependency>>
| Examine build dependencies for `kubernetes.yml` and add the objects found therein.

| <<fmp-git>>
| Check local `.git` directory and add build information as annotations.

| <<fmp-image>>
| Add the image name into a `PodSpec` of replication controller, replication sets and deployments, if missing.

| <<fmp-name>>
| Add a default name to every object which misses a name.

| <<fmp-project>>
| Add Maven coordinates as labels to all objects.

| <<fmp-service>>
| Create a default service if missing and extract ports from the Docker image configuration.

| <<fmp-healthcheck>>
| Configures livenessProbe and readinessProbe health checks using the liveness and readiness resources

|===

[[enrichers-standard]]
=== Standard Enrichers

Default enrichers are used for adding missing resources or adding metadata to given resource objects. The following default enhancers are availables out of the box

[[fmp-controller]]
==== fmp-controller

[[fmp-service]]
==== fmp-service

[[fmp-image]]
==== fmp-image

[[fmp-name]]
==== fmp-name

[[fmp-project]]
==== fmp-project

[[fmp-git]]
==== fmp-git

[[fmp-dependency]]
==== fmp-dependency

[[fmp-healthcheck]]
==== fmp-healthcheck

For the difference between the liveness and readiness probes, see http://kubernetes.io/docs/user-guide/pod-states/#container-probes

Example health checks:

```
<liveness>
    <initialDelaySeconds>30</initialDelaySeconds>
    <timeoutSeconds>3</timeoutSeconds>
    <getUrl>HTTP://:8080/alive</getUrl>
</liveness>
```

The readiness probe lets Kubernetes know if a given pod is ready to receive traffic from it's service. Traffic will only be routed to a pod if it's readiness probe executes correctly.
```
<readiness>
    <initialDelaySeconds>30</initialDelaySeconds>
    <timeoutSeconds>3</timeoutSeconds>
    <getUrl>HTTP://:8080/status</getUrl>
</readiness>
```

Kubernetes documentation on health checks:

* http://kubernetes.io/docs/user-guide/liveness/
* http://kubernetes.io/docs/user-guide/production-pods/#liveness-and-readiness-probes-aka-health-checks


[[enrichers-fabric8]]
=== Fabric8 Enrichers

Fabric8 enrichers are used for providing the connection to other components of the fabric8 Microservices platform. They are useful to add icons to to application or links to documentation sites.

[[f8-cd]]
==== f8-cd

[[f8-doc-link]]
==== f8-doc-link

[[f8-grafana-link]]
==== f8-grafana-link

[[f8-icon]]
==== f8-icon

== Enricher API

_howto write your own enricher and install them_
