
[[fabric8:setup]]
== *fabric8:setup*

This goal is for setting up maven projects to use the fabric8 maven plugin which either use an old version of the maven plugin or have not yet been modified to use it.

To use this goal type:

[source,sh,subs="attributes"]
----
mvn io.fabric8:fabric8-maven-plugin:{version}:setup
----

Now your pom.xml should be modified to use the fabric8 maven plugin. So you should be able to now run the following:

[source, sh]
----
mvn fabric8:run
----

To build the kubernetes manifests, docker image and to run your project on kubernetes or openshift!

=== Setting up your project by hand

if you prefer to do it all by hand, then add the following to your `pom.xml` file:


[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-maven-plugin</artifactId>
  <version>{version}</version>

  <configuration>
     ....
     <images>
        <!-- A single's image configuration -->
        <image>
          ...
          <build>
           ....
          </build>
        </image>
        ....
     </images>
  </configuration>

  <!-- Connect fabric8:resource and fabric8:build to lifecycle phases -->
  <executions>
    <execution>
       <id>fabric8</id>
       <goals>
         <goal>resource</goal>
         <goal>build</goal>
         <goal>helm</goal>
       </goals>
    </execution>
  </executions>
</plugin>
----


=== Migrating from 2.x fabric8-maven plugin

Note that the `fabric8:setup` goal is aimed at adding or updating fabric8-maven-plugin configurations for versions 3.x or later.

If you have a maven project with a 2.x fabric8-maven-plugin then we recommend you run the http://fabric8.io/guide/mavenFabric8Migrate.html[mvn fabric8:migrate] goal directly on your project to do the migration

[source, sh]
----
# in a fabric8-maven-plugin 2.x project
mvn fabric8:migrate
# now the project is using 3.x or later
----

Once the project is migrated to 3.x or later of the fabric8-maven-plugin you can then run this `fabric8:setup` goal at any time to update to the latest plugin and goals

