
[[fabric8:setup]]
== *fabric8:setup*

This goal is for setting up maven projects to use f8-m-p. It can be used to set up afresh this plugin in the `pom.xml` or to update an existing configuration.

To use this goal type:

[source,sh,subs="attributes"]
----
mvn io.fabric8:fabric8-maven-plugin:{version}:setup
----

Now your `pom.xml` is modified to use f8-m-p. The plugin will be bound some goals to Maven execution phases, so you can test it by running:

[source, sh]
----
mvn clean install
----

After this, a Docker image from your application is created (if some of the default generators could detect your setup) and the Kubernetes and OpenShift descriptors are created in `target/classes/META-INF/fabric8`.

.Manual Setup
Alternatively, if you prefer to do it all by hand, then add the following to your `pom.xml` file:


[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-maven-plugin</artifactId>
  <version>{version}</version>

  <configuration>
     ....
     <images>
        <!-- A single's image configuration -->
        <image>
          ...
          <build>
           ....
          </build>
        </image>
        ....
     </images>
  </configuration>

  <!-- Connect fabric8:resource and fabric8:build to lifecycle phases -->
  <executions>
    <execution>
       <id>fabric8</id>
       <goals>
         <goal>resource</goal>
         <goal>build</goal>
         <goal>helm</goal>
       </goals>
    </execution>
  </executions>
</plugin>
----

The setup can be influenced with the following configuration options:

.Setup configuration
[cols="1,5,1"]
|===
| Element | Description | Property

| *updateVersion*
| If set to `true` then an already existing plugin configuration will be updated. Otherwise an existing configuration is left untouched. Default is `true`.
| `updateVersion`

| *useVersionProperty*
| Whether we should use a version property for the plugin which is defined in a dedicates `<properties>` section with the name `fabric8.maven.plugin.version`
| `useVersionProperty`

| *generateBackupPoms*
| Controls whether a backup pom should be created when the `pom.xml` is modified. Ddefault is `true`.
| `generateBackupPoms`

| *backupPomFileName*
| Name of the backup file to create. Default is `${basedir}/pom.xml-backup`
| `backupPomFileName`
|===
