
[[fabric8:apply]]
== *fabric8:apply*

This goal will take all the kubernetes resources generated by the <<fabric8:resource>> goal and apply them into the current kubernetes cluster.

[source,sh,subs="attributes"]
----
mvn install fabric8:apply
----

Its usually simpler to just use the <<fabric8:deploy>> goal which performs a build and runs `fabric8:apply`:

[source,sh,subs="attributes"]
----
mvn fabric8:deploy
----

The resources applied are from `target/classes/META-INF/fabric8/kubernetes/*.yml` if using a Kubernetes cluster or `target/classes/META-INF/fabric8/openshift/*.yml` if you are using an OpenShift cluster

You can delete the kubernetes resources deployed into kubernetes via `fabric8:apply` via the <<fabric8:undeploy>> goal

[source,sh,subs="attributes"]
----
mvn fabric8:undeploy
----

If you have built your code and docker image but find some issue with the generated manifests; you can update the configuration of the <<fabric8:resource>> command or modify the YAML files in `src/main/fabric8` and then run:

[source,sh,subs="attributes"]
----
mvn fabric8:resource fabric8:apply
----

Which will skip the building of the java code, running unit tests and generating the docker build via <<fabric8:build>> but will only regenerate the manifests and apply them. This can help speed up the round trip time when fixing up resource generation issues.
