
[[generators]]
= Generators

The usual way to define Docker images is with the plugin configuration as explained in <<fabric8:build>>. This can either be done completly within the pom.xml or by refering to an external Dockerfile. Since fabric8-maven-plugin includes our https://github.com/fabric8io/docker-maven-plugin[docker-maven-plugin] the way how images are built is identical.

However, this plugin provides an additional route for defining image configurations. This is done by so called _Generators_. A generator is a Java component providing an auto-detection mechanism for certain build type like a Spring Boot build or a plain Java build. As soon as a generator detects that it is applicable it will be called with the list of images configured in the pom.xml. Typically a generator only creates dynamically an image configuration if this list is empty. But a generator is free to also add new images to an existing list or even change the current image list.

You can easily create your own generator as explained in <<generators-api, Generator API>>. This section however will focus on existing generators and how you can configure them.

By default, this plugin includes already a set of generators,  which are explained in detail below. These generators are enabled by default, but you can easil disable them or only select a certain set of generators. Each generator has a _name_, which is unique for a generator.

The generator configuration is embedded in a `<generator>` configuration section:

[[generator-example]]
.Example for a generator configuration
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<plugin>
  ....
  <configuration>
    ....
    <generator> <!--1-->
      <includes> <!--2-->
        <include>spring-boot</include>
      </includes>
      <config> <!--3-->
        <spring-boot> <!--4-->
          <alias>ping</alias>
        </spring-boot>
      </config>
    </generator>
  </configuration>
</plugin>
----
<1> Start of generators' configuration.
<2> Generators can be included and excluded. Includes have precedence, and the generators are called in the given order.
<3> Configuration for individual generators.
<4> The config is a map of supported config values. Each section is embedded in a tag named after the generator.

Generators can be configured with a `<generator>` section. The following sub-elements are supported.

.Generator configuration
[cols="1,6"]
|===
| Element | Description

| `<includes>`
| Contains one ore more `<include>` elements with generator names which should be included. If given, only this list of generators are included in this given order. The order is important because by default only the first matching generator kicks in.

| `<excludes>`
| Holds one or more `<exclude>` elements with generator names to exclude. This mean all detected generators are used except the ones mentioned in this section.

| `<config>`
| Configuration for all generators. Each generator support a specific set of configuration values as described in the documentation. The subelements of this section are generator names to configure. E.g. for generator `spring-boot`, the sub-element is called `<spring-boot>`. This element then holds the specific generator configuration like `<name>` for specifying the final image name. See above for an example.
|===

Beside the specifying generator configuration in the plugin's configuration it can be set with properties, too:

.Example generator property config
[source, sh]
----
mvn -Dfabric8.generator.spring-boot.alias="myapp"
----

The general scheme is a prefix `fabric8.generator.` followed by the unique generator name and then the generator specific key.

`fabric8-maven-plugin` comes with a set of default generators which are described in the next secion <<generators-fabric8, Fabric8 Generators>>. These are enabled by default. In addition, custom generators can be easily added. There are two ways to include generators:

.Plugin dependency

You can declare the generator holding jars as dependency to this plugin as shown in this example

[source, xml]
----
<plugin>
  <artifactId>fabric8-maven-plugin</artifactId>
  ....
  <depedencies>
    <dependency>
      <groupId>io.acme</groupId>
      <artifactId>mygenerator</artifactId>
      <version>1.0</version>
    <dependency>
  </dependencies>
</plugin>
----

.Compile time depdendency

Alternatively and if you application code comes with a custom generator you can set the global configuration option `useProjectClasspath` (property: `fabric8.useProjectClasspath`) to true. In this case also the project artifact and its dependencies are looked for genertors. See <<generators-api, Generator API>> for details how to write your own generators.

[[generators-default]]
== Default Generators

All default generators examine the build information for certain aspect and generate a Docker build information on the fly. They can be configured to a certrain degree, where the configuration is generator specific.



There are some configuration options which are shared by all generators:

[[generator-options-common]]
.Common generator options
[cols="1,6,1"]
|===
| Element | Description | Property

| *from*
| This is the base image from where to start when creating the images. By default the generators make an opinionated decision for the base image which are described in the respective generator section.
| `fabric8.generator.from`

| *fromMode*
| Whe using OpenShift S2I builds the base image can be either a plain docker image (mode: `docker`) or a reference to an https://docs.openshift.com/container-platform/3.3/architecture/core_concepts/builds_and_image_streams.html[ ImageStreamTag] (mode: `istag`). In the case of an ImageStreamTag, `from` has to be specified in the form `namespace/image-stream:tag`. The mode takes only effect when running in OpenShift mode.
| `fabric8.generator.fromMode`

| *alias*
| An alias name for referencing this image in various other parts of the configuration. This is also used in the log output. The default alias name is the name of the generator.
| `fabric8.generator.alias`

| *name*
| The Docker image name used when doing Docker builds. For OpenShift S2I builds its the name of the image stream. This can be a pattern as descibed in <<image-name-placeholders, Name Placeholders>>. The default is `%g/%a:%l`.
| `fabric8.generator.name`

| *merge*
| When this set to `true`, then the generator _adds_ to an existing image configuration. By default this is disabled, so that a generator only kicks in when there are no other image configurations in the build, which are either configured directly for a `fabric8:build` or already by a generator which has been run previously.
|
|===

When used as properties they can be directly referenced with the property names above.

[[generator-spring-boot]]
=== Spring Boot

The name of this generator is `spring-boot` and gets activated when it finds a `spring-boot-maven-plugin` among the configured plugins. This plugin can be also a included as a dependency. It will use the following base image by default, but as explained <<generator-options-common, above>> and can be changeda `from` configuration.

[[spring-boot-from]]
.Spring-Boot Base Images
[cols="1,4,4"]
|===
| | Docker Build | S2I Build | ImageStream

| *Community*
| `fabric8/java-alpine-openjdk8-jdk`
| `fabric8/s2i-java`
| `fabric8-java`

| *Red Hat*
| `jboss-fuse-6/fis-java-openshift`
| `jboss-fuse-6/fis-java-openshift`
| `fis-java-openshift`
|===

These images refer always to the latest tag. The _Red Hat_ base images are selected, when the plugin itself is a Red Hat supported version (which is detected by the plugins version number).

When a `fromMode` of `istag` is used to specify an `ImageStreamTag` and when no `from` is given, then as default the `ImageStreamTag` `fis-java-openshift` in the namespace `openshift` is chosen. If you are using a RedHat variation of this plugin (i.e. if the version is ending with `-redhat`), then a `fromMode` of `istag` is the default, otherwise its `fromMode = "docker"` which use the a plain Docker image reference for the S2I builder image.

The following additional configuration options can be set:

.Spring-Boot configuration options
[cols="1,6,1"]
|===
| Element | Description | Default

| *webPort*
| Port to expose as service
| 8080

| *jolokiaPort*
| Port of the Jolokia agent exposed by the base image
| 8778

| *prometheusPort*
| Port of the Prometheus jmx_exporter exposed by the base image
| 9779
|===

=== Java Applications

This generator is named `java-exec` and is responsible to start up arbitrary Java application. It kicks in if eithe the main class is explicitely configured in this generator's configuration or when it finds a singel class with a `public static void main(String[] args)` method. If it finds more than one class, the generator is a no op.

It use the same default images as the <<spring-boot-from, Spring Boot generator>>.

Beside the common configuration parameters described in the table <<generator-options-common, Commong Generator Options>> it knows the following additional configuration options:

.Java Application configuration options
[cols="1,6,1"]
|===
| Element | Description | Default

| *mainClass*
| Main class to call. If not given a class is tried to be found by scanning `target/classes` for a single class with a main method. If no if found or more than one is found, this generator does nothing.
|

| *webPort*
| Port to expose as service
| 8080

| *jolokiaPort*
| Port of the Jolokia agent exposed by the base image
| 8778

| *prometheusPort*
| Port of the Prometheus jmx_exporter exposed by the base image
| 9779
|===

[[generator-karaf]]
=== Karaf

This generator named `karaf` kicks in when the build uses a `karaf-maven-plugin`. By default the following base images are used:

[[generator-karaf-from]]
.Karaf Base Images
[cols="1,4,4"]
|===
| | Docker Build | S2I Build

| *Community*
| `fabric8/s2i-karaf`
| `fabric8/s2i-karaf`

| *Red Hat*
| `jboss-fuse-6/fis-karaf-openshift`
| `jboss-fuse-6/fis-karaf-openshift`
|===

When a `fromMode` of `istag` is used to specify an `ImageStreamTag` and when no `from` is given, then as default the `ImageStreamTag` `fis-karaf-openshift:2.0` in the namespace `openshift` is chosen.

In addition to the  <<generator-options-common, common generator options>> this generator can be configured with the following options:

.Karaf configuration options
[cols="1,6,1"]
|===
| Element | Description | Default

| *baseDir*
| Directory within the generated image where to put the detected artefacts into. Change this only if the base image is changed, too.
| `/deployments`

| *jolokiaPort*
| Port of the Jolokia agent exposed by the base image. Set this to 0 if you don't want to expose the Jolokia port.
| 8778

| *mainClass*
| Main class to call. If not given first a check is performed to detect a fat-jar (see above). Next a class is tried to be found by scanning `target/classes` for a single class with a main method. If no if found or more than one is found, then this generator does nothing.
|

| *user*
| User and/or group under which the files should be added. The syntax of this options is descriped in <<config-image-build-assembly-user, Assembly Configuration>>.
| `jboss:jboss:jboss`

| *webPort*
| Port to expose as service, which is supposed to be the port of a web application. Set this to 0 if you don't want to expose a port.
| 8080
|===

[[generators-api]]
== Generator API

WARNING: The API is still a bit in flux and will be documented later. Please refer to the  https://github.com/fabric8io/fabric8-maven-plugin/blob/master/generator/api/src/main/java/io/fabric8/maven/generator/api/Generator.java[Generator] Interface in the meantime.
