
[[introduction]]
= Introduction

The *fabric8-maven-plugin* (f8-m-p) brings your Java applications on to http://kubernetes.io/[Kubernetes] and https://www.openshift.com/[OpenShift].
It provides a tight integration into http://maven.apache.org[Maven] and benefits from the build configuration already provided.
This plugin focus on two tasks: _Building Docker images_ and _creating Kubernetes and OpenShift resource descriptors_.
It can be configured very flexibly and supports multiple configuration models for creating: A _Zero-Config_ setup allows for a quick ramp-up with some opinionated defaults.
For more advanced requirements, an _XML configuration_ provides additional configuration options which can be added to the `pom.xml`.
For the full power, in order to tune all facets of the creation, external _resource fragments_ and _Dockerfiles_ can be used.
A docker compose configuration can be also used to bring up docker compose deployments on a Kubernetes/OpenShift cluster.

[[building-images]]
== Building Images

The <<fabric8:build>> goal is for creating Docker images containing the actual application. These then can be deployed later on Kubernetes or OpenShift.
It is easy to include build artifacts and their dependencies into these images.
This plugin uses the assembly descriptor format from the http://maven.apache.org/plugins/maven-assembly-plugin/[maven-assembly-plugin] to specify the content which will be added to the image.
That images can then be pushed to public or private Docker registries with <<fabric8:push>>.

Depending on the operational mode, for building the actual image either a Docker daemon is used directly or an https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html#docker-build[OpenShift Docker Build] is performed.

A special <<fabric8:watch>> goal allows for reacting to code changes and automatic recreation of images or copying new artifacts into running containers.

These image related features are inherited from the https://github.com/fabric8io/docker-maven-plugin[fabric8io/docker-maven-plugin] which is part of this plugin.

[[resource-descriptors]]
== Kubernetes and OpenShift Resources

Kubernetes and OpenShift resource descriptors can be created or generated from existing docker compose with <<fabric8:resource>>.
These files are packaged within the Maven artifacts and can be deployed to a running orchestration platform with <<fabric8:apply>>.

Typically you only specify a small part of the real resource descriptors which will be enriched by this plugin with various extra information taken from the `pom.xml`.
This drastically reduces boilerplate code for common scenarios.

== Configuration

As mentioned already there are four levels of configuration:

* *Zero-Config* mode makes some very opinionated decisions based on what is present in the pom.xml like what base image to use or which ports to expose.
This is great for starting up things and for keeping quickstart applications small and tidy.

* *XML plugin configuration* mode is similar to what https://fabric8io.github.io/docker-maven-plugin/#example[docker-maven-plugin] provides.
This allows for type-safe configuration with IDE support, but only a subset of possible resource descriptor features is provided.

* *Kubernetes &amp; OpenShift resource fragments* are user provided YAML files that can be _enriched_ by the plugin. This allows expert users to use a plain configuration file with all their capabilities, but also to add project specific build information and avoid boilerplate code.


* *Docker Compose* can be used to bring up docker compose deployments on a Kubernetes/OpenShift cluster. This requires minimum to no knowledge of Kubernetes/OpenShift deployment process.

The following table gives an overview of the different models

.Configuration Models
[cols="1,4,4"]
|===
| Model | Docker Images | Resource Descriptors

| *Zero-Config*
| <<generators, Generators>> are used to create Docker image configurations. Generators can detect certain aspects of the build (e.g. whether Spring Boot is used) and then choose some default like the base image, which ports to expose and the startup command. The can be configured, but offer only a few options.
| Default <<enrichers, Enrichers>> will create a default _Service_ and _Deployment_ (_DeploymentConfig_ for OpenShift) when no other resource objects are provided. Depending on the image they can detect which port to expose in the service. As with Generators, Enrichers support a limited set of configuration options.

| *XML configuration*
| f8-m-p inherits the XML based configuration for building images from the https://fabric8io.github.io/docker-maven-plugin/#docker:build[docker-maven-plugin] and provides the same functionality. It supports an http://maven.apache.org/components/plugins/maven-assembly-plugin/assembly.html[assembly descriptor] for specifying the content of the Docker image.
| A subset of possible resource objects can be configured with a dedicated XML syntax. With a decent IDE you get autocompletion on most object and inline documentation for the available configuration elements. The provide configuration can be still enhanced by Enhancers which is useful for adding e.g. labels and annotation containing build or other information.

| *Resource Fragments* and *Dockerfiles*
| Like the docker-maven-plugin f8-m-p supports <<external-dockerfile,external Dockerfiles>> too, which are referenced from the plugin configuration.
| Resource descriptors can be provided as external YAML files which specify a skeleton. This skeleton is then filled by Enrichers which add labels and more. Maven properties within these files are resolved to thier values. With this model you can use every Kubernetes / OpenShift resource object with all their flexibility, but still get the benefit of adding build information.

| *Docker Compose*
| All above methods can works with docker compose configuration.
| The plugin converts docker compose descriptors into more detailed Kubernetes/OpenShift deployment resources. These resource descriptors or externally YAML files can be used to specify the application skeleton. This skeleton is then filled by Enrichers which add labels and more. Maven properties within these files are resolved to their values. With this model you can use every Kubernetes / OpenShift resource objects with all their flexibility, but still get the benefit of adding build information.
| A `dokcercompose.yml` can have a `:build` key that specifies how to build docker image, but at present this feature is not supported.
|===


== Examples

Let's have a look at some code. The following examples will demonstrate all three configurations variants:

[[zero-config]]
=== Zero-Config

This minimal but full working example `pom.xml` shows how a simple spring boot application can be dockerized and prepared for Kubernetes and OpenShift. The full example can be found in directory https://github.com/fabric8io/fabric8-maven-plugin/tree/master/samples/zero-config[samples/zero-config].

.Example
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-maven-sample-zero-config</artifactId>
  <version>{version}</version>
  <packaging>jar</packaging>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId> <!--1-->
    <version>1.5.5.RELEASE</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId> <!--2-->
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId> <!--3-->
      </plugin>
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId> <!--4-->
        <version>{version}</version>
      </plugin>
    </plugins>
  </build>
</project>
----
<1> This minimalistic spring boot application uses the spring-boot parent POM for setting up dependencies and plugins
<2> The Spring Boot web starter dependency enables a simple embedded Tomcat for serving Spring MVC apps
<3> The `spring-boot-maven-plugin` is responsible for repackaging the application into a fat jar, including all dependencies and the embedded Tomcat
<4> The `fabric8-maven-plugin` enables the automatic generation of a Docker image and Kubernetes / OpenShift descriptors including this Spring application.

This setup make some opinionated decisions for you:

* As base image https://github.com/fabric8io-images/java/tree/master/images/jboss/openjdk8/jdk[fabric8/java-jboss-openjdk8-jdk] is chosen which enables https://www.jolokia.org[Jolokia] and https://github.com/prometheus/jmx_exporter[jmx_exporter]. It also comes with a sophisticated https://github.com/fabric8io-images/run-java-sh[startup script].
* It will create a Kubernetes http://kubernetes.io/docs/user-guide/deployments/[Deployment] and a http://kubernetes.io/docs/user-guide/services/[Service] as resource objects
* It exports port 8080 as the application service port (and 8778 and 9779 for Jolokia and jmx_exporter access, respectively)

These choices can be influenced by configuration options as decribed in <<generator-spring-boot,Spring Boot Generator>>.

To start the Docker image build, you simply run

[source,bash]
----
mvn package fabric8:build
----

This will create the Docker image against a running Docker daemon (which must be accessible either via Unix Socker or with the URL set in `DOCKER_HOST`). Alternatively, when using `mvn -Dfabric8.mode=openshift package fabric8:build` and connected to an OpenShift cluster, then a Docker build will be performed on OpenShift which at the end creates an https://docs.openshift.com/enterprise/3.1/architecture/core_concepts/builds_and_image_streams.html[ImageStream].

To deploy the resources to the cluster call

[source,bash]
----
mvn fabric8:resource fabric8:deploy
----

By default a _Service_ and a _Deployment_ object pointing to the created Docker image is created. When running in OpenShift mode, a _Service_ and _DeploymentConfig_ which refers the _ImageStream_ created with `fabric8:build` will be installed.

Of course you can bind all those fabric8-goals to execution phases as well, so that they are called along with standard lifecycle goals like `install`. For example, to bind the building of the Kubernetes resource files and the Docker images, add the following goals to the execution of the f-m-p:

.Example for lifecycle bindings
[source, xml, indent=0]
----
<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-maven-plugin</artifactId>

  <!-- ... -->

  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
        <goal>build</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

If you'd also like to automatically deploy to Kubernetes each time you do a `mvn install` you can add the `deploy` goal:

.Example for lifecycle bindings with automatic deploys for mvn install
[source, xml, indent=0]
----
<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-maven-plugin</artifactId>

  <!-- ... -->

  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
        <goal>build</goal>
        <goal>deploy</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

=== XML Configuration

WARNING: XML based configuration is implemented only partially and not recommended to use right now.

Although the Zero-config mode with its generators can be tweaked with options up to a certain degree. In many cases more flexibility and power is required, though. For this an XML based plugin configuration can be use, much similar to the https://fabric8io.github.io/docker-maven-plugin/#configuration[XML configuration] used by `docker-maven-plugin`.

The plugin configuration can be roughly divided into the following sections:

* A global configuration options are responsible for tuning the behaviour of plugin goals
* ``<images>`` section which defines the Docker <<image-configuratuon,images>> to build. It has the https://fabric8io.github.io/docker-maven-plugin/#image-configuration[same syntax] as the similar configuration of `docker-maven-plugin` (except that `<run>` and `<external>` sub-elements are ignored)
* `<resource>` is used to defined the resource descriptors for deploying on an OpenShift or Kuberneres cluster.
* `<generator>` is for configuring <<generators,generators>> which are responsible for creating images. Generators are used as an alternative to a dedicates `<images>` section.
* `<enricher>` is used to configure various aspects of <<enrichers,enrichers>> for creating or enhancing resource descriptors.

A working example can be found in the  https://github.com/fabric8io/fabric8-maven-plugin/tree/master/samples/xml-config[samples/xml-config] directory. An extract of the plugin configuration is shown in the next example

.Example for an XML configuration
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<configuration>
  <images>  <!--1-->
    <image>
      <name>xml-config-demo:1.0.0</name>
      <!-- "alias" is used to correlate to the containers in the pod spec -->
      <alias>camel-app</alias>
      <build>
        <from>fabric8/java</from>
        <assembly>
          <basedir>/deployments</basedir>
          <descriptorRef>artifact-with-dependencies</descriptorRef>
        </assembly>
        <env>
          <JAVA_LIB_DIR>/deployments</JAVA_LIB_DIR>
          <JAVA_MAIN_CLASS>org.apache.camel.cdi.Main</JAVA_MAIN_CLASS>
        </env>
      </build>
    </image>
  </images>

  <resources> <!--2-->
    <labels> <!--3-->
      <all>
        <group>quickstarts</group>
      </all>
    </labels>

    <deployment> <!--4-->
      <name>${project.artifactId}</name>
      <replicas>1</replicas>

      <containers> <!--5-->
        <container>
          <alias>camel-app</alias> <!--6-->
          <ports>
            <port>8778</port>
          </ports>
          <mounts>
            <scratch>/var/scratch</scratch>
          </mounts>
        </container>
      </containers>

      <volumes> <!--7-->
        <volume>
          <name>scratch</name>
          <type>emptyDir</type>
        </volume>
      </volumes>
    </deployment>

    <services> <!--8-->
      <service>
        <name>camel-service</name>
        <headless>true</headless>
      </service>
    </services>
  </resources>
</configuration>
----
<1> Standard docker-maven-plugin configuration for building one single Docker image
<2> Kubernetes / OpenShift resources to create
<3> Labels which should be applied globally to all resource objects
<4> Definition of a http://kubernetes.io/docs/user-guide/deployments/[Deployment] to create
<5> Container to include in the deployment
<6> An _alias_ is used to correlate a container's image with the image definition in the `<images>` section where each image carry an alias. Can be omitted if only a single image is used
<7> http://kubernetes.io/docs/user-guide/volumes/[Volume] definitions used in a Deployment's _ReplicaSet_
<8> One or more http://kubernetes.io/docs/user-guide/services/[Service] definitions.

The XML resource configuration is based on plain Kubernetes resource objects. For creating OpenShift resource descriptor an automatic conversion will happen, e.g. from Kubernetes http://kubernetes.io/docs/user-guide/deployments/[Deployment] to an OpenShift https://docs.openshift.com/enterprise/3.0/dev_guide/deployments.html[DeploymentConfig].

=== Resource Fragments

The third configuration option is to use an external configuration in form of YAML resource descriptors which are located in the  `src/main/fabric8` directory. Each resource get is own file, which contains some skeleton of a resource description. The plugin will pick up the resource, enriches it and the combines all to a single `kubernetes.yml` and `openshift.yml`. Within these descriptor files you are can freely use any Kubernetes feature. Note, that in order to support simultaneously both OpenShift and Kubernetes, there is currently no way to specify OpenShift feature only this way (but this might change).

Let's have a look at an example from https://github.com/rhuss/fabric8-maven-plugin/tree/master/samples/external-resources[samples/external-resources]. This is a plain spring-boot application, whose images are auto generated like in the <<zero-config, Zero-Config>> case. The resource fragments are in `src/mainfabric8`.

.Example fragment "deployment.yml"
[source,yaml,indent=0,subs="verbatim,quotes,attributes"]
----
  spec:
    replicas: 1
    template:
      spec:
        volumes:
          - name: config
            gitRepo:
              repository: 'https://github.com/jstrachan/sample-springboot-config.git'
              revision: 667ee4db6bc842b127825351e5c9bae5a4fb2147
              directory: .
        containers:
          - volumeMounts:
              - name: config
                mountPath: /app/config
            env:
              - name: KUBERNETES_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        serviceAccount: ribbon
----

As you can see, there is no `metadata` section as expected for each Kubernetes resource object. This section will be created automatically by fabric8-maven-plugin. The object's `Kind`, if not given, will be extracted from the filename. In this case its a `Deployment` because the file is called `deployment.xml`. For each supported resource type such a mapping exists. In addition you could specify a name in like in `myapp-deployment.xml` to give the resource a fixed name. Otherwise it will be automatically extracted from project information (i.e. the artificact id).

Here also the reference to the image is missing. In this case it will be automatically connected to the image you are building with this plugin (And you already know, that the image definition comes either from a generator or by a dedicated image plugin configuration).

=== Docker Compose

The fourth configuration option is to provide an external Docker Compose file. The following are some ways to specify docker-compose files.

1. Put the Docker Compose file into `src/main/fabric8-compose` directory in the project space (only one file is supported at the moment).

2. Locate the Docker Compose file path using the plugin configuration, as shown in following `pom.xml` example.


.Example fragment "pom.xml"
[source, xml, indent=0]
----
<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-maven-plugin</artifactId>

  <!-- ... -->

  <configuration>
    <composeFile>docker-compose.yaml</composeFile>
  </configuration>

  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
        <goal>build</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

As you can see in `pom.xml`, the `composeFile` section under plugin `configuration` is used to provide the Docker Compose file path. It should be a relative path from the directory containing the `pom.xml` file.

If the execution configuration includes the `resource` goal (as shown in the `pom.xml` file above), the plugin will process the Docker Compose file and generate Kubernetes/OpenShift resource descriptors during the build.
Resources can be also generated using the <<fabric8:resource>> goal directly.
The Docker Compose option is implemented using http://kompose.io[kompose] project.

A working example can be found in the  https://github.com/fabric8io/fabric8-maven-plugin/tree/master/samples/docker-compose[samples/docker-compose]


NOTE: For building images there is also an alternative mode using external Dockerfiles, in addition to the XML based configuration. Refer to <<build-overview, fabric8:build>> for details.

'''

Enrichment of resource fragments can be fine tune by using profile sub-directories. For more details see <<profiles, Profiles>>.

Now that we have seen some examples for the various ways how this plugin can be used, the following sections will describe the plugin goals and extension points in detail.
