---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: "@ignore@"
      prometheus.io/port: "9779"
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/fabric8-maven-sample-zero-config
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: "@ignore@"
      prometheus.io/scrape: "true"
      fabric8.io/scm-tag: HEAD
    labels:
      expose: "true"
      app: fabric8-maven-sample-zero-config
      provider: fabric8
      version: 3.5-SNAPSHOT
      group: io.fabric8
    name: fabric8-maven-sample-zero-config
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: fabric8-maven-sample-zero-config
      provider: fabric8
      group: io.fabric8
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: "@ignore@"
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: "@ignore@"
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json?var-project=fabric8-maven-sample-zero-config&var-version=3.5-SNAPSHOT
      fabric8.io/scm-tag: HEAD
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/fabric8-maven-sample-zero-config
    labels:
      app: fabric8-maven-sample-zero-config
      provider: fabric8
      version: 3.5-SNAPSHOT
      group: io.fabric8
    name: fabric8-maven-sample-zero-config
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: fabric8-maven-sample-zero-config
      provider: fabric8
      group: io.fabric8
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "@ignore@"
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json?var-project=fabric8-maven-sample-zero-config&var-version=3.5-SNAPSHOT
          fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/fabric8-maven-sample-zero-config
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/git-branch: "@ignore@"
          fabric8.io/scm-tag: HEAD
        labels:
          app: fabric8-maven-sample-zero-config
          provider: fabric8
          version: 3.5-SNAPSHOT
          group: io.fabric8
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8-maven-sample-zero-config:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: fabric8-maven-sample-zero-config:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      expose: "true"
      app: fabric8-maven-sample-zero-config
      provider: fabric8
      version: 3.5-SNAPSHOT
      group: io.fabric8
    name: fabric8-maven-sample-zero-config
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: fabric8-maven-sample-zero-config