#
# Copyright 2016 Red Hat, Inc.
#
# Red Hat licenses this file to you under the Apache License, version
# 2.0 (the "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#

---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      provider: fabric8
      app: volume-enricher-storage-class-835
      version: 3.5-SNAPSHOT
      group: io.fabric8.devops.apps
      expose: "true"
    name: fabric8-docker-registry
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
    selector:
      app: volume-enricher-storage-class-835
      provider: fabric8
      group: io.fabric8
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: cheese
    labels:
      app: volume-enricher-storage-class-835
      provider: fabric8
      version: 3.5-SNAPSHOT
      group: io.fabric8
    name: fabric8-docker-registry-storage
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      provider: fabric8
      app: volume-enricher-storage-class-835
      version: 3.5-SNAPSHOT
      group: io.fabric8.devops.apps
    name: fabric8-docker-registry
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        provider: fabric8
        app: volume-enricher-storage-class-835
        group: io.fabric8
    template:
      metadata:
        labels:
          provider: fabric8
          app: volume-enricher-storage-class-835
          version: 3.5-SNAPSHOT
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: registry:2
          imagePullPolicy: IfNotPresent
          name: fabric8-docker-registry
          ports:
          - containerPort: 5000
            name: http
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
          - mountPath: /var/lib/registry
            name: fabric8-docker-registry-storage
            readOnly: false
        initContainers:
        - command:
          - chmod
          - "777"
          - /var/lib/registry
          image: busybox
          imagePullPolicy: IfNotPresent
          name: fmp-volume-permission
          volumeMounts:
          - mountPath: /var/lib/registry
            name: fabric8-docker-registry-storage
        volumes:
        - name: fabric8-docker-registry-storage
          persistentVolumeClaim:
            claimName: fabric8-docker-registry-storage

