---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      springboot-app: ""